---
title: "Intro to time series wrangling & viz"
author: "Jennifer Truong"
date: "2/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Attach packages
library(tidyverse)
library(here)
library(lubridate)
library(tsibble)
library(feasts)
library(slider)
```

## Read in data
```{r}
toolik <- read_csv(here("data", "toolikweather.csv"))
```
### Convert this into a tsibble

```{r}
toolik_ts <- toolik %>%
  mutate(date = lubridate::mdy(date)) %>%
  as_tsibble(key = NULL,
             index = date)
```

Seasonality looks dominant here.

```{r}
ggplot(data = toolik_ts,
       aes(x = date, y = mean_airtemp)) +
  geom_line()
```

## Use `index_by()` function to aggregate time series information by intervals we specify

```{r}
toolik_month <- toolik_ts %>%
  index_by(yr_mo = ~yearmonth(.)) %>%
  summarize(monthly_mean_temp = mean(mean_airtemp,
                                     na.rm = TRUE))

ggplot(data = toolik_month,
       aes(x = yr_mo, y = monthly_mean_temp)) +
  geom_line() +
  facet_wrap(~month(yr_mo, label = TRUE))
```
Aggregate by week:
```{r}
toolik_weekly <- toolik_ts %>%
  index_by(weekly = ~yearweek(.)) %>%
  summarize(
    weekly_airtemp = mean(mean_airtemp, na.rm = TRUE),
    min_airtemp = min(mean_airtemp)
  )

head(toolik_weekly)
```

